Update and rename WoT-UseCases-Template-20240710.yml to WoT-UseCases-…
w3c/wot-usecases pull request #295
Opened 2024-07-11 15:04 UTC by egekorkan

- Removing date from file name
- Removing placeholder text in the title since it is extra step to delete it

2024-07-11 15:19 UTC, egekorkan commented
I am also noticing some issues:
- There is too much information that is asked that I am not able to answer. What will we extract from all questions starting with Potential Adopters, Applications?
- We should add existing github issue. It can be that there is an issue already tracking this.

2024-07-11 19:37 UTC, TallTed requested changes

2024-07-11 19:37 UTC, TallTed commented on .github/ISSUE_TEMPLATE/WoT-UseCases-Template.yml
>  description: This is the latest UseCases Iusse Template. Please use this issue template to suggest a new use case to be added to the WoT standards.
```suggestion
description: This is the latest WoT Use Case Issue Template. Please use this issue template to suggest a new use case to be added to the WoT standards.
```

2024-07-12 01:41 UTC, chachamimm approved these changes
I agree.

2024-07-17 11:35 UTC, merged