New Use Case Template Proposal
w3c/wot-usecases pull request #300
Opened 2024-08-05 11:15 UTC by egekorkan

After talking with @chachamimm , I would like to provide a new use case template based on my experience in writing #296 and my expectations as a spec editor. This one specifically focuses on identifying gaps, which is my interest as a spec editor. 

This can seem a bit radical since it does not contain a lot of the fields present in the other use case templates we have seen so far. 

My main goal in this new template is addressing the following:

A use case submission should come from someone with the question of “I want to make sure that {my use case} is possible with WoT. However, due to lack of {gap}, I am not able to solve this in a standardized way.”

Since we need to assess the use case, we need more information:

- Some information about the background of the use case, such as some text, Industry or Domain
- How WoT is already used: TDs, Discovery, Bindings, Profile, Scripting
- Problem and Gap

2024-08-05 13:14 UTC, chachamimm reviewed
I think the your new use case template is concise and easy to understand. 

I think the use case template should be concise and easy for submitters to understand. 
Because submitters don't have much acknowledge of WoT and don't have enough time to write their use cases into the use case template.

But [WoT-UseCases-Template.yml](https://github.com/w3c/wot-usecases/blob/main/.github/ISSUE_TEMPLATE/WoT-UseCases-Template.yml) is the result that we have been discussing at Use Cases call, so I would like to discuss how to combine their contents.

I would like to start to collect use cases as soon as possible. For that purpose, I would like to fix the use case template as soon as possible.

I

2024-08-05 13:45 UTC, egekorkan commented
@chachamimm thank you for the reply and review.

> I think the use case template should be concise and easy for submitters to understand.

I agree.

> Because submitters don't have much acknowledge of WoT

This should not be the case from my point of view and there is proof of many organizations/people willing to submit a use case where they already use WoT. If they are not using WoT, they should submit another type of use case. **The analysis in that case would be very different.** It would probably result in us advising or consulting them on how to adopt WoT for their use case. I do not have resources to do this type of activity. Plus, we have use cases from WoT adopters that are enough to keep us occupied for a multiple months (probably 1-2 years).

> But [WoT-UseCases-Template.yml](https://github.com/w3c/wot-usecases/blob/main/.github/ISSUE_TEMPLATE/WoT-UseCases-Template.yml) is the result that we have been discussing at Use Cases call, so I would like to discuss how to combine their contents.

My proposal is quite radical and is not possible to combine with the other one. However, I have integrated some of the discussions/results from the other one. As slightly suggested by @k-toumura, I am open to having multiple "use case" templates. One would be this PR's proposal and another one would be from potential adopters where they give more information about their IoT (potentially not WoT) use case.

2024-08-05 21:38 UTC, TallTed requested changes

2024-08-05 21:38 UTC, TallTed commented on .github/ISSUE_TEMPLATE/use-case-template.yml
> +      description: Please enter your desired form of contact (e.g. Email, GitHub account name). Write "Separate" if you want to provide this in another way.
```suggestion
      description: Please enter your desired form of contact (e.g., email, GitHub account name). Write "Separate" if you want to provide this in another way.
```

2024-08-05 21:38 UTC, TallTed commented on .github/ISSUE_TEMPLATE/use-case-template.yml
> +      description: If your use case is from a specific domain, please provide here.
```suggestion
      description: If your use case is from a specific domain, please identify it here.
```

2024-08-05 21:38 UTC, TallTed commented on .github/ISSUE_TEMPLATE/use-case-template.yml
> +      description: Give a basic, non-technical introduction of the use case
```suggestion
      description: Give a basic, non-technical introduction to the use case.
```

2024-08-05 21:38 UTC, TallTed commented on .github/ISSUE_TEMPLATE/use-case-template.yml
> +      description: How do you already use the Web of Things specifications such as Thing Description, Discovery, Bindings, Profiles, Scripting API? If you are not using WoT, please write "None".
I suggest linking each of these titles to their web location.
```suggestion
      description: How do you already use Web of Things specifications such as Thing Description, Discovery, Bindings, Profiles, Scripting API? If you are not using WoT, please write "None".
```

2024-08-05 21:38 UTC, TallTed commented on .github/ISSUE_TEMPLATE/use-case-template.yml
> +      description: What kind of protocols, devices, data types, existing standards are present in the environment of the use case?
```suggestion
      description: What kind(s) of protocol, device, data type, and/or existing standard are present in the environment of the use case?
```

2024-08-05 21:38 UTC, TallTed commented on .github/ISSUE_TEMPLATE/use-case-template.yml
> +      description: What is the problem you want to highlight with this use case? What is missing in the specifications? Remove irrelevant specifications.
```suggestion
      description: What is the problem you want to highlight with this use case? What is missing in the specifications? (Remove irrelevant specifications from this list.)
```

2024-08-05 21:38 UTC, TallTed commented on .github/ISSUE_TEMPLATE/use-case-template.yml
> +      description: Do you already have a technical solution in mind? Please provide example TDs, specification text, code or similar.
```suggestion
      description: Do you already have a technical solution in mind? Please provide example TDs, specification text, code, or similar.
```

2024-08-05 21:38 UTC, TallTed commented on .github/ISSUE_TEMPLATE/use-case-template.yml
> +      description: Do you have other information you wish to provide?
```suggestion
      description: Do you have any other information you wish to provide?
```

2024-08-06 08:32 UTC, egekorkan commented
Thank you @TallTed for the corrections! :)

2024-08-06 11:40 UTC, chachamimm reviewed
@TallTed , thank you.

2024-09-04 11:39 UTC, merged