Create userstory-requirement.md
w3c/wot-usecases pull request #305
Opened 2024-10-24 13:31 UTC by mmccool

Initial user-story template for discussion.  To be used by other TFs to create databases of user stories that can then be submitted to the UC TF for inclusion in the UC&R document.

2024-10-31 13:08 UTC, mmccool commented on REQUIREMENTS/userstory-requirement.md
> +- **Link to at least one Use Case or Use Case Category (e.g. "ease of use")**
```suggestion
- **Link to at least one Use Case or Use Case Category (e.g. "ease of use")**
    - Propose a new category if necessary, linking to at least one use case
```

2024-11-07 15:49 UTC, mmccool commented
Did some updates based on the discussion in the TD call on Thursday Nov 7, would like to merge and create a YAML issue template based on it.

2024-11-07 21:44 UTC, TallTed requested changes

2024-11-07 21:44 UTC, TallTed commented on REQUIREMENTS/userstory-requirement.md
> +into a sentence template of the following form:
```suggestion
Simple form for user-story based requirements.  While we have split 
the elements into Who/What/Why, each of these should be written as if they fit
into a sentence template of the following form:
```

2024-11-07 21:44 UTC, TallTed commented on REQUIREMENTS/userstory-requirement.md
> +and the "Why" can be interpreted as a Functional Requirement.
```suggestion
Each slot should be concise — no more than a single line.
The "What" can be interpreted as a Technical Requirement,
and the "Why" can be interpreted as a Functional Requirement.
```

2024-11-07 21:44 UTC, TallTed commented on REQUIREMENTS/userstory-requirement.md
>  - May also be a Condition that needs to be satisfied (e.g. "minimize size")
```suggestion
- May also be a Condition that needs to be satisfied (e.g., "minimize size")
```

2024-11-07 21:44 UTC, TallTed commented on REQUIREMENTS/userstory-requirement.md
>  - **Link to at least one Use Case or Use Case Category (e.g. "ease of use")**
```suggestion
- **Link to at least one Use Case or Use Case Category (e.g., "ease of use")**
```

2024-11-07 21:44 UTC, TallTed commented on REQUIREMENTS/userstory-requirement.md
> +- Free-form extra details only if needed
```suggestion
- Free-form extra details; only if needed
```

2024-11-07 21:44 UTC, TallTed commented on REQUIREMENTS/userstory-requirement.md
> +- Extra details should be maintained in a separate document that links back this user story
```suggestion
- Extra details should be maintained in a separate document that links back to this user story
```

2024-12-11 12:44 UTC, mmccool commented
Will merge after some updates to make it consistent with the new template, but we do have the old requirements-template.md still in the REQUIREMENTS directory and we should do some cleanup and archival.  Let's merge and create and issue to do the cleanup.

2024-12-11 12:45 UTC, merged